controller:
  service:
    enabled: true
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # If using AWS
    type: LoadBalancer
    port: 80
    targetPort: 80
